name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Install OS tools'
        run: |
          sudo apt-get install expect
      - uses: actions/checkout@v3

      - name: Maven Build
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
